config/routes.rb
Artistnxt::Application.routes.draw do
  
  get "fanregister" => 'pages#fanregister', as: :fanregister
  get "admin/videos"
  get "/admin/video_details/:cid/" => 'admin#video_details', as: :admin_video_details
  match "/admin/save_video" => 'admin#save_video', via: [:post], as: :admin_save_video
  match "/admin/removevideo/:cid/" => "admin#removevideo", as: :removevideo, via: [:delete]
  get "admin/music"
  get "/admin/music_details/:cid/" => 'admin#music_details', as: :admin_music_details
  match "/admin/removemusic/:cid/" => "admin#removemusic", as: :removemusic, via: [:delete]
  
  get '/news/:id' => 'pages#readnews', as: :read_admin_news
  match '/news/save_ordering' => 'admin_news#save_ordering', via: [:post]
  resources :admin_news

  match '/cart/confirm' => 'carts#confirm', via: [:post]
  match '/confirm_music_purchase' => 'payment_notifications#confirm_music_purchase', via: [:post]
  get '/cart/checkout' => 'carts#checkout'
  match '/cart/remove_item' => 'carts#remove_item', via: [:delete]
  
  resources :order_items

  resources :orders

  resources :cart_items

  resources :carts

  get '/page/:alias' => 'pages#content_page', as: :content_page
  
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  
  match "payment/notifications" => 'payment_notifications#create', via: [:post]
  get "admin/settings"
  match "admin/save_settings" => 'admin#save_settings', via: [:post]  
  match "/admin/save_user" => 'admin#save_user', via: [:post], as: :admin_save_user
  match "/admin/save_new_user" => 'admin#save_new_user', via: [:post], as: :admin_save_new_user
  get "admin/dashboard"
  get "admin/users"
  get "admin/artists"
  get "admin/artist"
  get "admin/new_user"
  get "admin/edit_user"
  get "admin/fan"
  get "admin/fans"
  get "admin/users_json"
  get "admin/slides"
  get "profile/index"
  get "profile/follower_fans"
  get "profile/artist_following"
  
  match '/slides/save_ordering' => 'slides#save_ordering', via: [:post]
  match '/music_categories/save_ordering' => 'music_categories#save_ordering', via: [:post]
  match '/plans/save_ordering' => 'plans#save_ordering', via: [:post]
  match '/subscriptions/clear_invoice' => 'subscriptions#clear_invoice',via: [:get],  as: :clear_invoice
  match '/subscriptions/update' => 'subscriptions#update',via: [:post]
  match '/music_purchases/complete_order/:id' => 'music_purchases#complete_order',via: [:get], as: :admin_music_purchase_complete
  
  match '/application/upload_photo' => 'application#upload_photo', via: [:post]
  match '/application/check_email' => 'application#check_email', via: [:get]
  
  get '/artist/:id' => 'pages#dashboard', as: :artist_dashboard
  get '/fan/:id' => 'pages#dashboard', as: :fan_dashboard
  get '/dashboard/:id' => 'pages#dashboard', as: :user_dashboard
  get '/become_fan/:artistid/:fanid' => 'pages#become_fan', as: :become_fan
  get '/add_friend/:sender_id/:receiver_id' => 'profile#add_friend', as: :add_friend
  get '/remove_friend/:sender_id/:receiver_id' => 'profile#remove_friend', as: :remove_friend
  get '/accept_friend_request/:sender_id/:receiver_id' => 'profile#accept_friend_request', as: :accept_friend_request
  get '/my_friends' => 'profile#my_friends', as: :my_friends
  get '/peding_friend_requests' => 'profile#peding_friend_requests', as: :peding_friend_requests
  get '/awaiting_friend_requests' => 'profile#awaiting_friend_requests', as: :awaiting_friend_requests
  get '/artist_fantistics/:artist_id' => 'pages#artist_fantistics', as: :artist_fantistics
  
  get '/countries/get_states' => 'countries#get_country_states'
  
  get '/video/watch/:id' => 'videos#watch', as: :watch_video
  get '/video/remove_watch/:user_id/:id' => 'videos#remove_watch', as: :remove_video_watch
  get '/video/clear_watch_list' => 'videos#clear_watch_list', as: :clear_watch_list
  get '/video/make_favorite/:user_id/:id' => 'videos#make_favorite', as: :make_video_favorite
  get '/video/remove_favorite/:user_id/:id' => 'videos#remove_favorite', as: :remove_video_favorite
  get '/news/read/:id' => 'news#read', as: :read_news
  get '/event/details/:id' => 'events#details', as: :event_details
  
  get '/admin/make_featured_artist/:artist_id/:value' => 'admin#make_featured_artist', as: :make_featured_artist
  get '/admin/removeuser/:user_id/' => 'admin#removeuser', as: :removeuser
  
  get '/renew_subscription/:subscription_id' => 'pages#renew_subscription', as: :renew_subscription
  get '/confirmation_subscription/:subscription_id/:plan_id' => 'pages#confirmation_subscription', as: :confirmation_subscription
  get '/subscription_confirmed/:subscription_id/:plan_id' => 'pages#subscription_confirmed', as: :subscription_confirmed
  get '/pending_invoice/:subscription_id' => 'pages#pending_invoice', as: :pending_invoice
  get '/confirm_pending_invoice/:subscription_id' => 'pages#confirm_pending_invoice', as: :confirm_pending_invoice
  get '/download_music/:unqiue_key' => 'pages#download_music', as: :download_music
  get '/download_free_music/:id' => 'pages#download_free_music', as: :download_free_music
  get '/my_musics' => 'profile#my_musics', as: :my_musics
  get '/my_purchases' => 'profile#my_purchases', as: :my_purchases
  get '/my_music_sales' => 'profile#my_music_sales', as: :my_music_sales
  get '/favorite_videos' => 'profile#favorite_videos', as: :favorite_videos
  get '/watch_history' => 'profile#watch_history', as: :watch_history
  
  get '/my_order_details/:id' => 'profile#my_order_details',via: [:get], as: :my_order_details
  get '/pay_my_order/:id' => 'profile#pay_my_order',via: [:get], as: :pay_my_order
  
  match '/make_comment' => 'comments#create', via: [:post]
  
  resources :states

  resources :countries

  scope "/admin" do
    resources :contents
    resources :music_categories
    resources :music_purchases
    resources :plans
    resources :slides
    resources :subscriptions
  end

  devise_for :users, :controllers => { :registrations  => "users/registrations", :sessions => "users/sessions", :omniauth_callbacks => "users/omniauth_callbacks", :confirmations  => "users/confirmations" }
  
  devise_scope :user do
    get 'users' => 'devise/sessions#new'
    get 'signup/artist' => 'users/registrations#new', :user => { :user_type => 'artist' }
    get 'signup/fan' => 'users/registrations#new', :user => { :user_type => 'fan' }
    
    match 'users/omniauth_callbacks_confirm' => 'users/omniauth_callbacks#confirm_user_provider_signup', via: [:post]
  end
  
  resources :users do
    resources :videos, :audios, :news, :events
  end
  
  get "genres" => 'pages#genres'
  get "signup" => 'pages#signup'
  
  root 'pages#home'
  

  

end

app/models/content.rb
class Content < ActiveRecord::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_filter :is_admin
  protect_from_forgery except: :save_ordering
  layout 'admin_layouts'

  # GET /contents
  # GET /contents.json
  def index
    @search = params[:search].to_s
    if @search.length > 0
      searchText = '%'+@search+'%'
      @contents = Content.where("title LIKE ?",searchText).order('ordering ASC').paginate(:page => params[:page], :per_page => 10)
    else
      @contents = Content.order('ordering ASC').paginate(:page => params[:page], :per_page => 10)    
    end
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
    @form_action = 'create'
  end

  # GET /contents/1/edit
  def edit
    @form_action = 'update'
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)
    
    @content.alias = @content.title.parameterize

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render action: 'show', status: :created, location: @content }
      else
        format.html { render action: 'new' }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    #render text: content_params and return
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:title, :alias, :text, :published, :hits, :ordering, :position)
    end
    
    def is_admin
      if current_user.role != 'administrator'
        flash[:alert] = 'You are not authorized to view this resource!'
        redirect_to(root_path)
      end
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_for(@content, url: {action: @form_action}) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <dl>
  <dt><%= f.label :title %></dt>
  <dd><%= f.text_field :title, class: "login_inp required" %></dd>
  </dl>
  
  <dl>
  <dt><%= f.label :position %></dt>
  <dd><%= f.select(:position, [['Top Menu', 'top'], ['Middle Right', 'right'], ['Footer Menu', 'footer']]) %></dd>
  </dl>
  
  <dl>
  <dt><%= f.label :text %></dt>
  <dd style="width: 65.4%;"><%= f.text_area :text, :class => "tinymce", :rows => 20, :cols => 120 %></dd>
  </dl>
  
  <dl>
  <dt><%= f.label :published %></dt>
  <dd><%= f.check_box :published %></dd>
  </dl>
  
  <dl>
  <dt>&nbsp;</dt>
  <dd><%= f.submit "Submit", class: "login"  %></dd>
  </dl>
<% end %>

<script>
tinymce.init({
    selector: "textarea",
    theme: "modern",
    plugins: [
         "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
         "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
         "save table contextmenu directionality emoticons template paste textcolor"
   ],
   toolbar: "insertfile undo redo | fontselect fontsizeselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | preview media fullpage | forecolor backcolor emoticons"
 }); 
</script>

app/views/contents/edit.html.erb
<% content_for :page_title do %>
  <title>ArtistNXT | Editing content</title>
<% end %>

<div class="profiletitle">Editing content</div>
<div class="clr">&nbsp;</div>

<div id="ddtags" class="ddtags-full-width">
  
  <%= render 'form' %>
  
  <dl>			
    <dt><%= link_to 'Show', @content %></dt>
    <dd><%= link_to 'Back', contents_path %></dd>
  </dl>
  
</div>

app/views/contents/index.html.erb
<% content_for :page_title do %>
  <title>ArtistNXT | Contents Manager</title>
<% end %>

<div class="profiletitle">Contents Manager</div>
<div class="clr">&nbsp;</div>

<div class="searchWrap">
	<div class="searchbox">
                <form id="searchForm" name="searchForm" action="" method="get">
                  <div class="searchboxinner">
                    <input type="text" name="search" class="textbox1" value="<%=h(@search)%>"/>
                    <input type="submit" value="Search" class="btn"/>
                    <input style="margin-left:4px;" type="button" class="btn" value="Reset" onclick="document.searchForm.search.value='';document.searchForm.submit();">
                  </div>
                </form>		
	</div>
	<div class="add-new"><%= link_to 'New Content', new_content_path %></div>
	<div class="clr">&nbsp;</div>
</div>
<div class="tableWrap">
  <form id="dataFormItem" name="dataFormItem" action="" method="post">
    <table class="table">
           <thead>
                  <tr>
                    <th style="width: 50px;">#</th>
                    <th>Title</th>
                    <th>Alias</th>
		    <th>Position</th>
                    <th style="width: 125px;">Published</th>
                    <!--th style="width: 125px;">Ordering<a href="javascript:void(0);" onclick="saveOrdering();"><%= image_tag("/assets/filesave_icon.png") %></a></th-->
                    <th style="width: 150px;">Action</th>
                  </tr>
           </thead>
           <tbody>
                  <%
		    itemNo = 0
                    if params[:page].to_i > 1
		      itemNo = (params[:page].to_i - 1)*10
                    end
                    
                    @contents.each do |content|
                    itemNo = itemNo + 1
                  %>
                    <tr>
                      <td><%=itemNo%></td>
                      <td>
                        <%=link_to content.title, content %>
                      </td>
                      <td><%=content.alias %></td>
		      
		      <td><% content_position = case content.position
              when 'footer' then "Footer Menu"
              when 'right' then "Middle Right"
              else "Top Menu"
          end
          %>

        <%=content_position%></td>
                      
                      <td>
                        <%if content.published%>
                          <img src="/assets/tick_green_icon.png" alt="" />
                        <%else%>
                          <img src="/assets/unpublish_icon.png" alt="" />
                        <%end%>
                        
                      </td>
                      <!--td><input type="text" name="ordering[<%=content.id%>]" class="order_input" value="<%= content.ordering.to_i %>"/></td-->
                      <td>
                          <%= link_to image_tag("/assets/edit_icon.png"), edit_content_path(content) %>                          
                          &nbsp;&nbsp;&nbsp;
                          <%= link_to image_tag("/assets/delete_icon.png"), content, method: :delete, data: { confirm: 'Are you sure?' } %>
                      </td>
                    </tr>
                  <% end %>                  
           </tbody>
    </table>
    <%= will_paginate @content, :params=>{:search=>h(@search)} %>
  </form>
</div>
<script type="text/javascript">
function saveOrdering()
{
  if(jQuery('.order_input').length > 0)
  {    
    jQuery('#dataFormItem').attr('action','<%=plans_save_ordering_path%>').submit();
  }
}
</script>

app/views/contents/new.html.erb
<% content_for :page_title do %>
  <title>ArtistNXT | New Content</title>
<% end %>

<div class="profiletitle">New Content</div>
<div class="clr">&nbsp;</div>

<div id="ddtags" class="ddtags-full-width">
  
  <%= render 'form' %>
  
  <dl>
  <dt>&nbsp;</dt>
  <dd><%= link_to 'Back', contents_path %></dd>
  </dl>
</div>

app/views/contents/show.html.erb
<% content_for :page_title do %>
  <title>ArtistNXT | Content Details</title>
<% end %>

<div class="profiletitle">Content Details</div>
<div class="clr">&nbsp;</div>

<div id="ddtags" class="ddtags-full-width">

  <dl>
    <dt><strong>Title:</strong>:</dt>
    <dd><%= @content.title %></dd>
  </dl>
  
  <dl>			
    <dt><strong>Alias</strong>:</dt>
    <dd><%= @content.alias %></dd>
  </dl>
  
  <dl>			
    <dt><strong>Position</strong>:</dt>
    <dd><% content_position = case @content.position
              when 'footer' then "Footer Menu"
              when 'right' then "Middle Right"
              else "Top Menu"
          end
          %>

        <%=content_position%>
      </dd>
  </dl>
  
  <dl>			
    <dt><strong>Hits</strong>:</dt>
    <dd><%= @content.hits %></dd>
  </dl>
  
  <dl>			
    <dt><strong>Published</strong>:</dt>
    <dd>
      <% if @content.published
        %>
          <img src="/assets/tick_green_icon.png" alt="" />
        <%
        else
        %>
          <img src="/assets/unpublish_icon.png" alt="" />
        <%
        end
      %>
    </dd>
  </dl>
  
  <dl>			
    <dt><%= link_to 'Edit', edit_content_path(@content) %></dt>
    <dd><%= link_to 'Back', contents_path %></dd>
  </dl>

</div>