config/routes.rb
Artistnxt::Application.routes.draw do
  
  get "fanregister" => 'pages#fanregister', as: :fanregister
  get "admin/videos"
  get "/admin/video_details/:cid/" => 'admin#video_details', as: :admin_video_details
  match "/admin/save_video" => 'admin#save_video', via: [:post], as: :admin_save_video
  match "/admin/removevideo/:cid/" => "admin#removevideo", as: :removevideo, via: [:delete]
  get "admin/music"
  get "/admin/music_details/:cid/" => 'admin#music_details', as: :admin_music_details
  match "/admin/removemusic/:cid/" => "admin#removemusic", as: :removemusic, via: [:delete]
  
  get '/news/:id' => 'pages#readnews', as: :read_admin_news
  match '/news/save_ordering' => 'admin_news#save_ordering', via: [:post]
  resources :admin_news

  match '/cart/confirm' => 'carts#confirm', via: [:post]
  match '/confirm_music_purchase' => 'payment_notifications#confirm_music_purchase', via: [:post]
  get '/cart/checkout' => 'carts#checkout'
  match '/cart/remove_item' => 'carts#remove_item', via: [:delete]
  
  resources :order_items

  resources :orders

  resources :cart_items

  resources :carts

  get '/page/:alias' => 'pages#content_page', as: :content_page
  
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  
  match "payment/notifications" => 'payment_notifications#create', via: [:post]
  get "admin/settings"
  match "admin/save_settings" => 'admin#save_settings', via: [:post]  
  match "/admin/save_user" => 'admin#save_user', via: [:post], as: :admin_save_user
  match "/admin/save_new_user" => 'admin#save_new_user', via: [:post], as: :admin_save_new_user
  get "admin/dashboard"
  get "admin/users"
  get "admin/artists"
  get "admin/artist"
  get "admin/new_user"
  get "admin/edit_user"
  get "admin/fan"
  get "admin/fans"
  get "admin/users_json"
  get "admin/slides"
  get "profile/index"
  get "profile/follower_fans"
  get "profile/artist_following"
  
  match '/slides/save_ordering' => 'slides#save_ordering', via: [:post]
  match '/music_categories/save_ordering' => 'music_categories#save_ordering', via: [:post]
  match '/plans/save_ordering' => 'plans#save_ordering', via: [:post]
  match '/subscriptions/clear_invoice' => 'subscriptions#clear_invoice',via: [:get],  as: :clear_invoice
  match '/subscriptions/update' => 'subscriptions#update',via: [:post]
  match '/music_purchases/complete_order/:id' => 'music_purchases#complete_order',via: [:get], as: :admin_music_purchase_complete
  
  match '/application/upload_photo' => 'application#upload_photo', via: [:post]
  match '/application/check_email' => 'application#check_email', via: [:get]
  
  get '/artist/:id' => 'pages#dashboard', as: :artist_dashboard
  get '/fan/:id' => 'pages#dashboard', as: :fan_dashboard
  get '/dashboard/:id' => 'pages#dashboard', as: :user_dashboard
  get '/become_fan/:artistid/:fanid' => 'pages#become_fan', as: :become_fan
  get '/add_friend/:sender_id/:receiver_id' => 'profile#add_friend', as: :add_friend
  get '/remove_friend/:sender_id/:receiver_id' => 'profile#remove_friend', as: :remove_friend
  get '/accept_friend_request/:sender_id/:receiver_id' => 'profile#accept_friend_request', as: :accept_friend_request
  get '/my_friends' => 'profile#my_friends', as: :my_friends
  get '/peding_friend_requests' => 'profile#peding_friend_requests', as: :peding_friend_requests
  get '/awaiting_friend_requests' => 'profile#awaiting_friend_requests', as: :awaiting_friend_requests
  get '/artist_fantistics/:artist_id' => 'pages#artist_fantistics', as: :artist_fantistics
  
  get '/countries/get_states' => 'countries#get_country_states'
  
  get '/video/watch/:id' => 'videos#watch', as: :watch_video
  get '/video/remove_watch/:user_id/:id' => 'videos#remove_watch', as: :remove_video_watch
  get '/video/clear_watch_list' => 'videos#clear_watch_list', as: :clear_watch_list
  get '/video/make_favorite/:user_id/:id' => 'videos#make_favorite', as: :make_video_favorite
  get '/video/remove_favorite/:user_id/:id' => 'videos#remove_favorite', as: :remove_video_favorite
  get '/news/read/:id' => 'news#read', as: :read_news
  get '/event/details/:id' => 'events#details', as: :event_details
  
  get '/admin/make_featured_artist/:artist_id/:value' => 'admin#make_featured_artist', as: :make_featured_artist
  get '/admin/removeuser/:user_id/' => 'admin#removeuser', as: :removeuser
  
  get '/renew_subscription/:subscription_id' => 'pages#renew_subscription', as: :renew_subscription
  get '/confirmation_subscription/:subscription_id/:plan_id' => 'pages#confirmation_subscription', as: :confirmation_subscription
  get '/subscription_confirmed/:subscription_id/:plan_id' => 'pages#subscription_confirmed', as: :subscription_confirmed
  get '/pending_invoice/:subscription_id' => 'pages#pending_invoice', as: :pending_invoice
  get '/confirm_pending_invoice/:subscription_id' => 'pages#confirm_pending_invoice', as: :confirm_pending_invoice
  get '/download_music/:unqiue_key' => 'pages#download_music', as: :download_music
  get '/download_free_music/:id' => 'pages#download_free_music', as: :download_free_music
  get '/my_musics' => 'profile#my_musics', as: :my_musics
  get '/my_purchases' => 'profile#my_purchases', as: :my_purchases
  get '/my_music_sales' => 'profile#my_music_sales', as: :my_music_sales
  get '/favorite_videos' => 'profile#favorite_videos', as: :favorite_videos
  get '/watch_history' => 'profile#watch_history', as: :watch_history
  
  get '/my_order_details/:id' => 'profile#my_order_details',via: [:get], as: :my_order_details
  get '/pay_my_order/:id' => 'profile#pay_my_order',via: [:get], as: :pay_my_order
  
  match '/make_comment' => 'comments#create', via: [:post]
  
  resources :states

  resources :countries

  scope "/admin" do
    resources :contents
    resources :music_categories
    resources :music_purchases
    resources :plans
    resources :slides
    resources :subscriptions
  end

  devise_for :users, :controllers => { :registrations  => "users/registrations", :sessions => "users/sessions", :omniauth_callbacks => "users/omniauth_callbacks", :confirmations  => "users/confirmations" }
  
  devise_scope :user do
    get 'users' => 'devise/sessions#new'
    get 'signup/artist' => 'users/registrations#new', :user => { :user_type => 'artist' }
    get 'signup/fan' => 'users/registrations#new', :user => { :user_type => 'fan' }
    
    match 'users/omniauth_callbacks_confirm' => 'users/omniauth_callbacks#confirm_user_provider_signup', via: [:post]
  end
  
  resources :users do
    resources :videos, :audios, :news, :events
  end
  
  get "genres" => 'pages#genres'
  get "signup" => 'pages#signup'
  
  root 'pages#home'
  

  

end

app/models/music_category.rb
class MusicCategory < ActiveRecord::Base
  has_and_belongs_to_many :audios
  has_and_belongs_to_many :videos
  validates :name, presence: true
end

app/controllers/music_categories_controller.rb
class MusicCategoriesController < ApplicationController
  before_action :set_music_category, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_filter :is_admin
  protect_from_forgery except: :save_ordering
  layout 'admin_layouts'

  # GET /music_categories
  # GET /music_categories.json
  def index
    @search = params[:search].to_s
    if @search.length > 0
      searchText = '%'+@search+'%'
      @music_categories = MusicCategory.where("name LIKE ?",searchText).order('ordering ASC').paginate(:page => params[:page], :per_page => 10)
    else
      @music_categories = MusicCategory.order('ordering ASC').paginate(:page => params[:page], :per_page => 10)    
    end
  end

  # GET /music_categories/1
  # GET /music_categories/1.json
  def show
  end

  # GET /music_categories/new
  def new
    @music_category = MusicCategory.new
    @form_action = 'create'
  end

  # GET /music_categories/1/edit
  def edit
    @form_action = 'update'
  end

  # POST /music_categories
  # POST /music_categories.json
  def create
    @music_category = MusicCategory.new(music_category_params)

    respond_to do |format|
      if @music_category.save
        format.html { redirect_to @music_category, notice: 'Music category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @music_category }
      else
        format.html { render action: 'new' }
        format.json { render json: @music_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /music_categories/1
  # PATCH/PUT /music_categories/1.json
  def update
    respond_to do |format|
      if @music_category.update(music_category_params)
        format.html { redirect_to @music_category, notice: 'Music category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @music_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /music_categories/1
  # DELETE /music_categories/1.json
  def destroy
    @music_category.destroy
    respond_to do |format|
      format.html { redirect_to music_categories_url, notice: 'Music category was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  
  def save_ordering
    orderingData = params[:ordering]

    if orderingData!=nil && orderingData.length > 0
      orderingData.each do |orderItem|
        musicCatRow = MusicCategory.where("id = ?",orderItem[0]).take
        if musicCatRow!=nil && !musicCatRow.ordering.eql?(orderItem[1])
          musicCatRow.update(:ordering=>orderItem[1])
        end
      end
      allMusicCategories = MusicCategory.all().order('ordering ASC');
      if !allMusicCategories.nil?
        ordering = 1
        allMusicCategories.each do |item|
          item.update(:ordering=>ordering)
          ordering = ordering+1          
        end
      end 
      flash[:notice] = "Ordering was successfully saved."
      redirect_to(music_categories_path) and return
    else
      redirect_to('/') and return
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music_category
      @music_category = MusicCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def music_category_params
      params.require(:music_category).permit(:name, :desc, :show_at_home_page)
    end
    
    def is_admin
      if current_user.role != 'administrator'
        flash[:alert] = 'You are not authorized to view this resource!'
        redirect_to(root_path)
      end
    end
end

app/helpers/music_categories_helper.rb
module MusicCategoriesHelper
end

app/views/music_categories/_form.html.erb
<%= form_for(@music_category, url: {action: @form_action}) do |f| %>
  <% if @music_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@music_category.errors.count, "error") %> prohibited this music_category from being saved:</h2>

      <ul>
      <% @music_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <dl>
  <dt><%= f.label :name %>:</dt>
  <dd><%= f.text_field :name, class: "login_inp required" %></dd>
  </dl>
  
  <dl>
  <dt><%= f.label :desc %>:</dt>
  <dd><%= f.text_area :desc, class: "login_inp1" %></dd>
  </dl>
  
  <dl>
  <dt><%= f.label :show_at_home_page %></dt>
  <dd><%= f.check_box :show_at_home_page %></dd>
  </dl>
  
  <dl>
  <dt>&nbsp;</dt>
  <dd><%= f.submit "Submit", class: "login"  %></dd>
  </dl>
<% end %>

app/views/music_categories/edit.html.erb
<% content_for :page_title do %>
  <title>ArtistNXT | Editing Music Category</title>
<% end %>

<div class="profiletitle">Editing Music Category</div>
<div class="clr">&nbsp;</div>

<div id="ddtags">
  
  <%= render 'form' %>
  
  <dl>			
    <dt><%= link_to 'Show', @music_category %></dt>
    <dd><%= link_to 'Back', music_categories_path %></dd>
  </dl>
  
</div>

app/views/music_categories/index.html.erb
<% content_for :page_title do %>
  <title>ArtistNXT | Music Category Manager</title>
<% end %>

<div class="profiletitle">Music Category Manager</div>
<div class="clr">&nbsp;</div>

<div class="searchWrap">
	<div class="searchbox">
                <form id="searchForm" name="searchForm" action="" method="get">
                  <div class="searchboxinner">
                    <input type="text" name="search" class="textbox1" value="<%=h(@search)%>"/>
                    <input type="submit" value="Search" class="btn"/>
                    <input style="margin-left:4px;" type="button" class="btn" value="Reset" onclick="document.searchForm.search.value='';document.searchForm.submit();">
                  </div>
                </form>		
	</div>
	<div class="add-new"><%= link_to 'Add New', new_music_category_path %></div>
	<div class="clr">&nbsp;</div>
</div>

<div class="tableWrap">
  <form id="dataFormItem" name="dataFormItem" action="" method="post">
    <table class="table">
           <thead>
                  <tr>
                    <th style="width: 50px;">#</th>
                    <th>Name</th>
                    <th>Home page</th>                                        
                    <th style="width: 125px;">Ordering<a href="javascript:void(0);" onclick="saveOrdering();"><%= image_tag("/assets/filesave_icon.png") %></a></th>
                    <th style="width: 150px;">Action</th>
                  </tr>
           </thead>
           <tbody>
                  <%
                    rowNo = 0
                    if params[:page].to_i > 1
		      rowNo = (params[:page].to_i - 1)*10
                    end
                    @music_categories.each do |row|
                    rowNo = rowNo + 1
                  %>
                    <tr>
                      <td><%=rowNo%></td>                      
                      <td><%=link_to row.name, row %></td>		      
                      <td>
                        <%if (row.show_at_home_page)
                        %>
                          Yes
                        <%
                        else
                        %>
                          No
                        <%
                        end      
                        %>                        
                      </td>
                      <td><input type="text" name="ordering[<%=row.id%>]" class="order_input" value="<%= row.ordering.to_i %>"/></td>
                      <td>
                          <%= link_to image_tag("/assets/edit_icon.png"), edit_music_category_path(row) %>                          
                          &nbsp;&nbsp;&nbsp;
                          <%= link_to image_tag("/assets/delete_icon.png"), music_category_path(row),method: :delete, data: { confirm: 'Are you sure?' } %>
                      </td>
                    </tr>
                  <% end %>                  
           </tbody>
    </table>
    <%= will_paginate @music_categories, :params=>{:search=>h(@search)} %>
  </form>
</div>
<script type="text/javascript">
function saveOrdering()
{
  if(jQuery('.order_input').length > 0)
  {    
    jQuery('#dataFormItem').attr('action','<%=music_categories_save_ordering_path%>').submit();
  }
}
</script>

app/views/music_categories/new.html.erb
<% content_for :page_title do %>
  <title>ArtistNXT | New Music Category</title>
<% end %>

<div class="profiletitle">New Music Category</div>
<div class="clr">&nbsp;</div>

<div id="ddtags">
  
  <%= render 'form' %>
  
  <dl>
  <dt>&nbsp;</dt>
  <dd><%= link_to 'Back', music_categories_path %></dd>
  </dl>
</div>

app/views/music_categories/show.html.erb
<% content_for :page_title do %>
  <title>ArtistNXT | Music Category</title>
<% end %>

<div class="profiletitle">Music Category</div>
<div class="clr">&nbsp;</div>

<div id="ddtags">

  <dl>
    <dt><strong>Name</strong>:</dt>
    <dd><%= @music_category.name %></dd>
  </dl>
  
  <dl>			
    <dt>Description</dt>
    <dd><%= @music_category.desc %></dd>
  </dl>
  
  <dl>			
    <dt>At home page</dt>
    <dd>
      <%if (@music_category.show_at_home_page)
      %>
        Yes
      <%
      else
      %>
        No
      <%
      end      
      %>
    </dd>
  </dl>
  
  
  <dl>			
    <dt><%= link_to 'Edit', edit_music_category_path(@music_category) %></dt>
    <dd><%= link_to 'Back', music_categories_path %></dd>
  </dl>

</div>