config/routes.rb
Artistnxt::Application.routes.draw do
  
  get "fanregister" => 'pages#fanregister', as: :fanregister
  get "admin/videos"
  get "/admin/video_details/:cid/" => 'admin#video_details', as: :admin_video_details
  match "/admin/save_video" => 'admin#save_video', via: [:post], as: :admin_save_video
  match "/admin/removevideo/:cid/" => "admin#removevideo", as: :removevideo, via: [:delete]
  get "admin/music"
  get "/admin/music_details/:cid/" => 'admin#music_details', as: :admin_music_details
  match "/admin/removemusic/:cid/" => "admin#removemusic", as: :removemusic, via: [:delete]
  
  get '/news/:id' => 'pages#readnews', as: :read_admin_news
  match '/news/save_ordering' => 'admin_news#save_ordering', via: [:post]
  resources :admin_news

  match '/cart/confirm' => 'carts#confirm', via: [:post]
  match '/confirm_music_purchase' => 'payment_notifications#confirm_music_purchase', via: [:post]
  get '/cart/checkout' => 'carts#checkout'
  match '/cart/remove_item' => 'carts#remove_item', via: [:delete]
  
  resources :order_items

  resources :orders

  resources :cart_items

  resources :carts

  get '/page/:alias' => 'pages#content_page', as: :content_page
  
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  
  match "payment/notifications" => 'payment_notifications#create', via: [:post]
  get "admin/settings"
  match "admin/save_settings" => 'admin#save_settings', via: [:post]  
  match "/admin/save_user" => 'admin#save_user', via: [:post], as: :admin_save_user
  match "/admin/save_new_user" => 'admin#save_new_user', via: [:post], as: :admin_save_new_user
  get "admin/dashboard"
  get "admin/users"
  get "admin/artists"
  get "admin/artist"
  get "admin/new_user"
  get "admin/edit_user"
  get "admin/fan"
  get "admin/fans"
  get "admin/users_json"
  get "admin/slides"
  get "profile/index"
  get "profile/follower_fans"
  get "profile/artist_following"
  
  match '/slides/save_ordering' => 'slides#save_ordering', via: [:post]
  match '/music_categories/save_ordering' => 'music_categories#save_ordering', via: [:post]
  match '/plans/save_ordering' => 'plans#save_ordering', via: [:post]
  match '/subscriptions/clear_invoice' => 'subscriptions#clear_invoice',via: [:get],  as: :clear_invoice
  match '/subscriptions/update' => 'subscriptions#update',via: [:post]
  match '/music_purchases/complete_order/:id' => 'music_purchases#complete_order',via: [:get], as: :admin_music_purchase_complete
  
  match '/application/upload_photo' => 'application#upload_photo', via: [:post]
  match '/application/check_email' => 'application#check_email', via: [:get]
  
  get '/artist/:id' => 'pages#dashboard', as: :artist_dashboard
  get '/fan/:id' => 'pages#dashboard', as: :fan_dashboard
  get '/dashboard/:id' => 'pages#dashboard', as: :user_dashboard
  get '/become_fan/:artistid/:fanid' => 'pages#become_fan', as: :become_fan
  get '/add_friend/:sender_id/:receiver_id' => 'profile#add_friend', as: :add_friend
  get '/remove_friend/:sender_id/:receiver_id' => 'profile#remove_friend', as: :remove_friend
  get '/accept_friend_request/:sender_id/:receiver_id' => 'profile#accept_friend_request', as: :accept_friend_request
  get '/my_friends' => 'profile#my_friends', as: :my_friends
  get '/peding_friend_requests' => 'profile#peding_friend_requests', as: :peding_friend_requests
  get '/awaiting_friend_requests' => 'profile#awaiting_friend_requests', as: :awaiting_friend_requests
  get '/artist_fantistics/:artist_id' => 'pages#artist_fantistics', as: :artist_fantistics
  
  get '/countries/get_states' => 'countries#get_country_states'
  
  get '/video/watch/:id' => 'videos#watch', as: :watch_video
  get '/video/remove_watch/:user_id/:id' => 'videos#remove_watch', as: :remove_video_watch
  get '/video/clear_watch_list' => 'videos#clear_watch_list', as: :clear_watch_list
  get '/video/make_favorite/:user_id/:id' => 'videos#make_favorite', as: :make_video_favorite
  get '/video/remove_favorite/:user_id/:id' => 'videos#remove_favorite', as: :remove_video_favorite
  get '/news/read/:id' => 'news#read', as: :read_news
  get '/event/details/:id' => 'events#details', as: :event_details
  
  get '/admin/make_featured_artist/:artist_id/:value' => 'admin#make_featured_artist', as: :make_featured_artist
  get '/admin/removeuser/:user_id/' => 'admin#removeuser', as: :removeuser
  
  get '/renew_subscription/:subscription_id' => 'pages#renew_subscription', as: :renew_subscription
  get '/confirmation_subscription/:subscription_id/:plan_id' => 'pages#confirmation_subscription', as: :confirmation_subscription
  get '/subscription_confirmed/:subscription_id/:plan_id' => 'pages#subscription_confirmed', as: :subscription_confirmed
  get '/pending_invoice/:subscription_id' => 'pages#pending_invoice', as: :pending_invoice
  get '/confirm_pending_invoice/:subscription_id' => 'pages#confirm_pending_invoice', as: :confirm_pending_invoice
  get '/download_music/:unqiue_key' => 'pages#download_music', as: :download_music
  get '/download_free_music/:id' => 'pages#download_free_music', as: :download_free_music
  get '/my_musics' => 'profile#my_musics', as: :my_musics
  get '/my_purchases' => 'profile#my_purchases', as: :my_purchases
  get '/my_music_sales' => 'profile#my_music_sales', as: :my_music_sales
  get '/favorite_videos' => 'profile#favorite_videos', as: :favorite_videos
  get '/watch_history' => 'profile#watch_history', as: :watch_history
  
  get '/my_order_details/:id' => 'profile#my_order_details',via: [:get], as: :my_order_details
  get '/pay_my_order/:id' => 'profile#pay_my_order',via: [:get], as: :pay_my_order
  
  match '/make_comment' => 'comments#create', via: [:post]
  
  resources :states

  resources :countries

  scope "/admin" do
    resources :contents
    resources :music_categories
    resources :music_purchases
    resources :plans
    resources :slides
    resources :subscriptions
  end

  devise_for :users, :controllers => { :registrations  => "users/registrations", :sessions => "users/sessions", :omniauth_callbacks => "users/omniauth_callbacks", :confirmations  => "users/confirmations" }
  
  devise_scope :user do
    get 'users' => 'devise/sessions#new'
    get 'signup/artist' => 'users/registrations#new', :user => { :user_type => 'artist' }
    get 'signup/fan' => 'users/registrations#new', :user => { :user_type => 'fan' }
    
    match 'users/omniauth_callbacks_confirm' => 'users/omniauth_callbacks#confirm_user_provider_signup', via: [:post]
  end
  
  resources :users do
    resources :videos, :audios, :news, :events
  end
  
  get "genres" => 'pages#genres'
  get "signup" => 'pages#signup'
  
  root 'pages#home'
  

  

end

app/views/admin/artist.html.erb
<% content_for :page_title do %>
  <title>ArtistNXT | Artist Manager</title>
<% end %>

<div class="profiletitle">Artist Details</div>


<div id="ddtags" class="ddtags-full-width">
  <dl>
    <dt><strong>Name</strong>:</dt>
    <dd><%=@artistInfo.first_name+" "+@artistInfo.last_name%></dd>
  </dl>
  
  <dl>
    <dt><strong>Email</strong>:</dt>
    <dd><%= @artistInfo.email %></dd>
  </dl>
  
  <dl>
    <dt><strong>Country</strong>:</dt>
    <dd><%= getCountryName(@artistInfo.country_id) %></dd>
  </dl>
  
  <dl>
    <dt><strong>State</strong>:</dt>
    <dd><%= getStateName(@artistInfo.state_id) %></dd>
  </dl>
  
  <dl>
    <dt><strong>City</strong>:</dt>
    <dd><%= @artistInfo.city %></dd>
  </dl>
  
  <dl>
    <dt><strong>Zip Code</strong>:</dt>
    <dd><%= @artistInfo.zip %></dd>
  </dl>
  
  <dl>
    <dt><strong>Phone No</strong>:</dt>
    <dd><%= @artistInfo.phone %></dd>
  </dl>
  
  <dl>
    <dt><strong>Music Info</strong>:</dt>
    <dd><%= @artistInfo.music_info %></dd>
  </dl>
  
  <dl>
    <dt><strong>Category</strong>:</dt>
    <dd><%= @musicCatName %></dd>
  </dl>
  
  <dl>
    <dt><strong>Music description</strong>:</dt>
    <dd><%= @artistInfo.music_desc %></dd>
  </dl>
  
  <dl>
    <dt><strong>Label</strong>:</dt>
    <dd>
      <% if @artistInfo.music_label
      %>
        Yes
      <%
      else
      %>
        No
      <%
        end
      %>
    </dd>
  </dl>
  
    
  <dl>
    <dt><strong>Profile Photo</strong>:</dt>
    <dd><%= image_tag(getUserAvatar(@artistInfo,"large"),:width => "212") %></dd>
  </dl>
  
  <dl>			
    <dt>&nbsp;</dt>
    <dd><%= link_to 'Edit', admin_edit_user_path(:user_id=>@artistInfo.id) %> | <%= link_to 'Back', admin_artists_path %></dd>
  </dl>
</div>

app/views/admin/artists.html.erb
<% content_for :page_title do %>
  <title>ArtistNXT | Artist Manager</title>
<% end %>

<div class="profiletitle">Artist Manager</div>
<div class="clr">&nbsp;</div>
<div class="searchWrap clearfix">
      <div class="searchbox">
	  <form id="searchForm" name="searchForm" action="" method="get">
	    <div class="searchboxinner">
	      <input type="text" name="search" class="textbox1" value="<%=h(@search)%>"/>
	      <input type="submit" value="Search" class="btn"/>
	      <input style="margin-left:4px;" type="button" class="btn" value="Reset" onclick="document.searchForm.search.value='';document.searchForm.submit();">
		
	      <input type="hidden" name="sort_by" id="sort_by" value="<%=@sort_by%>" />
	      <input type="hidden" name="sort_dir" id="sort_dir" value="<%=@sort_dir%>" />
	    </div>
	  </form>		
      </div>
      
      <div class="exportWrap">
	<label>Export:</label><%= link_to image_tag("/assets/export_csv.gif"), admin_artists_path(format: "csv", search: @search, sort_by: @sort_by, sort_dir: @sort_dir) %>
      </div>
      <div class="clr">&nbsp;</div>
</div>
<div class="tableWrap">
  <form id="dataFormSlide" name="dataFormSlide" action="" method="post">
  <div class="table-responsive">
    <table class="table">
           <thead>
                  <tr>
                    <th style="width: 50px;">#</th>
                    <th><%=sortColumn('first_name', @sort_by, @sort_dir, 'Name').html_safe%></th>
  		    <th><%=sortColumn('email', @sort_by, @sort_dir, 'Email').html_safe%></th>
		    <th><%=sortColumn('created_at', @sort_by, @sort_dir, 'Register Date').html_safe%></th>
		    <th>Featured</th>
		    <th>Phone</th>
		    <th style="width: 150px;">Action</th>
                  </tr>
           </thead>
	   <tbody>
	      <%
		itemNo = 0
		if params[:page].to_i > 1
		  itemNo = (params[:page].to_i - 1)*10
		end
		@items.each do |item|
		itemNo = itemNo + 1
		
		user_name = item.first_name.to_s + " " + item.last_name.to_s
	      %>
		<tr>
		    <td><%=itemNo%></td>
		    <td><%= link_to user_name, artist_dashboard_path(id: item.id.to_s+':'+user_name.parameterize), target: "_blank" %></td>
		    <td><%=item.email.to_s%></td>
		    <td><%=item.created_at.to_s%></td>		    
		    <td>
		      <%if item.featured
		      %>
			<%= link_to image_tag("/assets/tick_green_icon.png"), make_featured_artist_path(:artist_id=>item.id,:value=>0) %>
		      <%
		      else
		      %>
			<%= link_to image_tag("/assets/unpublish_icon.png"), make_featured_artist_path(:artist_id=>item.id,:value=>1) %>
		      <%
			end
		      %>
		    </td>
		    <td><%=item.phone.to_s%></td>
		    <td>
			      <%= link_to image_tag("/assets/edit_icon.png"), admin_artist_path(:artist_id=>item.id)
			      %>                          
			      &nbsp;&nbsp;&nbsp;
			      <%= link_to image_tag("/assets/delete_icon.png"), removeuser_path(:user_id=>item.id),method: :get, data: { confirm: 'Are you sure?.All videos, news, events of this artist will be deleted' } %>
		    </td>
		  </tr>
	      <% end %>         
	   </tbody>
           
    </table>
    </div>
   <%= will_paginate @items, :params=>{:search=>h(@search)} %>
  </form>
</div>

app/views/admin/dashboard.html.erb
<% content_for :page_title do %>
  <title>ArtistNXT | Admin Dashboard</title>
<% end %>

<div class="profiletitle">Dashboard</div>
<div class="clr">&nbsp;</div>


<div class="icon-wrapper">
    <div class="icon">
        <a href="<%=admin_artists_path %>">
            <img alt="" src="/assets/icon-48-user.png">
            <span>Artists</span>
        </a>
    </div>
    <div class="icon">
        <a href="<%=contents_path %>">
            <img alt="" src="/assets/icon-48-article.png">
            <span>Contents</span>
        </a>
    </div>
    <div class="icon">
        <a href="<%=admin_fans_path %>">
            <img alt="" src="/assets/icon-48-user.png">
            <span>Fans</span>
        </a>
    </div>
    <div class="icon">
        <a href="<%=admin_slides_path %>">
            <img alt="" src="/assets/icon-48-media.png">
            <span>Sliders</span>
        </a>
    </div>
    <div class="icon">
        <a href="<%=plans_path %>">
            <img alt="" src="/assets/icon-48-plans.png">
            <span>Plans</span>
        </a>
    </div>
    <div class="icon">
        <a href="<%=music_categories_path %>">
            <img alt="" src="/assets/icon-48-media.png">
            <span>Music Categories</span>
        </a>
    </div>
    <div class="icon">
        <a href="<%=admin_settings_path %>">
            <img alt="" src="/assets/icon-48-config.png">
            <span>Settings</span>
        </a>
    </div>
</div>

app/views/admin/edit_user.html.erb
<% content_for :page_title do %>
  <title>ArtistNXT | User Manager</title>
<% end %>

<div class="profiletitle">User Details</div>


<div id="ddtags" class="ddtags-full-width">
  <%= form_for(@userInfo, :url => admin_save_user_path, :html => { :method => :post }) do |f| %>
      <%= f.hidden_field :id %>
      <dl>	
          <dt><%= label_tag(:first_name, "First Name") %>:</dt>
          <dd><%= f.text_field :first_name, class: "login_inp" %></dd>
       </dl>
      <dl>			
          <dt><%= label_tag(:last_name, "Last Name") %>:</dt>
          <dd><%= f.text_field :last_name, class: "login_inp" %></dd>
       </dl>
       
       <dl>			
          <dt><%= label_tag(:email, "Email Address") %>:</dt>
          <dd><%= f.email_field :email, class: "login_inp" %></dd>
       </dl>
       <%if @userInfo.role!="administrator"%>
       
	    <dl>			
	       <dt><%= label_tag(:phone, "Phone No") %>:</dt>
	       <dd><%= f.telephone_field(:phone, class: "login_inp") %></dd>
	    </dl>
	    <%if @userInfo.user_type == "artist"%>
	     <dl>			
		<dt><%= label_tag(:biography, "Biography") %></dt>
		<dd><%= f.text_area(:biography, class: "login_inp1") %></dd>
	    </dl>	
	    <%end%>
	     <dl>			
		<dt><%= label_tag(:country_id, "Country") %>:</dt>
		<dd>
		   <%= f.collection_select(:country_id, Country.all, :id, :country_name, {:prompt => "Please Select Your Country"}, {:class => "login_inp2"}) %>
		</dd>
	     </dl>        
	     <dl class="countryDependent"<%=(@userInfo.country_id.to_i!=223)?" style=display:none;":""%>>			
		<dt><%= label_tag(:state_id, "State") %>:</dt>
		<dd>
		   <div id="country_states_wrapper"> 
		     <%= render partial: 'countries/state_select', locals: {country_id: @userInfo.country_id, state_id: @userInfo.state_id} %>
		   </div>
		</dd>
	     </dl>
	     
	     <dl>			
		<dt><%= label_tag(:city, "City") %>:</dt>
		<dd><%= f.text_field :city, class: "login_inp" %></dd>
	     </dl>
	     
	     <dl>			
		<dt><%= label_tag(:zip, "Zip Code") %>:</dt>
		<dd><%= f.text_field :zip, class: "login_inp" %></dd>
	     </dl>
	<%end%>
       <dl>			
          <dt><%= label_tag(:password, "Choose Password") %>:</dt>
          <dd><%= f.password_field :password, class: "login_inp", :autocomplete => "off" %> <i>(leave blank if you don't want to change it)</i></dd>
       </dl>       
       <dl>			
          <dt><%= label_tag(:password_confirmation, "Retype Password") %>:</dt>
          <dd><%= f.password_field :password_confirmation, class: "login_inp" %></dd>
       </dl>
       <%if @userInfo.role!="administrator"%>
       <dl>			
	    <dt>Profile Pic:</dt>
	    <dd>
	       <span><%= image_tag(getUserAvatar(@userInfo,"large"),:width => "212") %></span>
	       
	       <% if @userInfo.profile_photo.to_s!="" %>
	       <span><a href="javascript:void(0);" id="add_new_trigger">Remove and add new</a></span>
	       <% else %>
	       <span><a href="javascript:void(0);" id="add_new_trigger">Add new</a></span>
	       <% end %>
	    </dd>
	</dl>
	 
        <dl id="add_new_wrapper" style="display:none;">			
           <dt><%= label_tag(:profile_photo, "Upload Profile Photo") %>:</dt>
           <dd>
              <div id="queue"></div>
              <input id="photo_upload" name="photo_upload" type="file" >
              <div id="photo_preview" style="display:none;"></div>              
              <input type="hidden" value="" name="user[profile_photo]" id="user_profile_photo">
           </dd>
        </dl>
	<%end%>
       <dl>			
          <dt>&nbsp;</dt>
          <dd><%= f.submit "Update", class: "login" %></dd>
       </dl>
  <% end %>
  
  
  
  <dl>			
    <dt>&nbsp;</dt>
    <dd>
      <%if @userInfo.user_type == "artist"%>
	<%= link_to 'Back', admin_artists_path %>
      <%elsif @userInfo.user_type == "fan"%>
	<%= link_to 'Back', admin_fans_path %>
      <%elsif @userInfo.role == "administrator"%>
	<%= link_to 'Back', admin_users_path %>
      <%end%>
    </dd>
  </dl>
</div>
<%if @userInfo.role!="administrator"%>

<style type="text/css">
.preview_data {
   font-weight:bold;
}
label.invalid {
   color: #B61C1C;
}
.login_inp.required.invalid {
   border: 1px solid #B61C1C;
}
.login_inp2.required.invalid {
   border: 1px solid #B61C1C;
}
.uploadify-button {
   background-color: #B61C1C;
   border: none;
   padding: 0;
}
.uploadify:hover .uploadify-button {
   background-color: #B61C1C;
}
</style>


<script type="text/javascript">
jQuery(function() {
      jQuery('#add_new_trigger').click(function(){
	 jQuery('#add_new_wrapper').show();
      })
      
      jQuery('#photo_upload').uploadify({
	 'debug'    : false,
	 'fileSizeLimit' : '2MB',
	 'fileTypeDesc' : 'Image Files',
	 'fileTypeExts' : '*.gif; *.jpg; *.png', 
	 'multi'    : false,
	 'width'    : 100,
	 'method'   : 'post',
	 'fileObjName' : 'photo_upload',
	 'formData'     : {
		 'timestamp' : (new Date()).getTime(),
		 'token'     : (new Date()).getTime(),
		 'authenticity_token' : '<%= form_authenticity_token %>'
	 },
	 'swf'      : '<%= asset_path "uploadify/uploadify.swf" %>',
	 'uploader' : '/application/upload_photo',
	 'onSelect' : function(file) {
	    jQuery('#photo_preview').html('').hide();
	    jQuery('#final_photo_preview').html('').hide();
	    jQuery('#user_profile_photo').val('');
	 },
	 'onUploadSuccess' : function(file, data, response) {
	    jsonData = JSON.parse(data);	    
	    file.name = jsonData.files[0].name;
	    jQuery('#photo_preview').show().html('<img src="/uploads/tmp/'+file.name+'?d='+ (new Date()).getTime()+'" id="crop_target" width="100px" />');
	    jQuery('#final_photo_preview').show().html('<img src="/uploads/tmp/'+file.name+'?d='+ (new Date()).getTime()+'" id="crop_target" width="100px" />');
	    jQuery('#user_profile_photo').val(jsonData.files[0].name);
	 },
	 'onUploadError' : function(file, errorCode, errorMsg, errorString) {
	    alert('The file ' + file.name + ' could not be uploaded: ' + errorString);
	 },
	 'onUploadComplete' : function(file) {
	    
	    /*jQuery('#photo_preview').show().html('<img src="/uploads/tmp/'+file.name+'?d='+ (new Date()).getTime()+'" id="crop_target" width="100px" />');
	    jQuery('#final_photo_preview').show().html('<img src="/uploads/tmp/'+file.name+'?d='+ (new Date()).getTime()+'" id="crop_target" width="100px" />');
	    jQuery('#user_profile_photo').val(file.name);*/
	 }
      });
      jQuery('select#user_country_id').change(function(){
        var country_id = jQuery(this).val();
	if(country_id == 223)//us
	{
	  jQuery('.countryDependent').show();      
	  select_wrapper = jQuery('#country_states_wrapper');
	  jQuery('select', select_wrapper).attr('disabled', true);
	  url = "/countries/get_states?country_id="+country_id;
	  select_wrapper.load(url);  
	}
	else//hide state and zip
	{
	  jQuery('.countryDependent').hide();      
	  if(jQuery('#user_state_id').length > 0)
	     jQuery('#user_state_id').val('')
	}
      });
});
</script>
<%end%>

app/views/admin/fan.html.erb
<% content_for :page_title do %>
  <title>ArtistNXT | Fans Manager</title>
<% end %>

<div class="profiletitle">Fan Details </div>

<div id="ddtags">
  <dl>
    <dt><strong>Name</strong>:</dt>
    <dd><%=@fanInfo.first_name+" "+@fanInfo.last_name%></dd>
  </dl>
  
  <dl>
    <dt><strong>Email</strong>:</dt>
    <dd><%= @fanInfo.email %></dd>
  </dl>
  
  <dl>
    <dt><strong>Phone No</strong>:</dt>
    <dd><%= @fanInfo.phone %></dd>
  </dl>
  
  <dl>
    <dt><strong>Country</strong>:</dt>
    <dd><%= getCountryName(@fanInfo.country_id) %></dd>
  </dl>
  
  <dl>
    <dt><strong>State</strong>:</dt>
    <dd><%= getStateName(@fanInfo.state_id) %></dd>
  </dl>
  
  <dl>
    <dt><strong>City</strong>:</dt>
    <dd><%= @fanInfo.city %></dd>
  </dl>
  
  <dl>
    <dt><strong>Zip Code</strong>:</dt>
    <dd><%= @fanInfo.zip %></dd>
  </dl>
  
  <dl>
    <dt><strong>Profile Photo</strong>:</dt>
    <dd><%= image_tag(getUserAvatar(@fanInfo,"large"),:width => "212") %></dd>
  </dl>
  
  <dl>			
    <dt>&nbsp;</dt>
    <dd><%= link_to 'Edit', admin_edit_user_path(:user_id=>@fanInfo.id) %> | <%= link_to 'Back', admin_fans_path %></dd>
  </dl>
</div>

app/views/admin/music_details.html.erb
<% content_for :page_title do %>
  <title>ArtistNXT | Music Details</title>
<% end %>

<div class="profiletitle">Music Details</div>
<div class="clr">&nbsp;</div>

<div id="ddtags">

  <dl>
    <dt><strong>Title:</strong>:</dt>
    <dd><%= @item.title %></dd>
  </dl>
  
  <dl>
    <dt><strong>Created By:</strong>:</dt>
    <dd><%= User.find(@item.user_id).first_name+' ' +User.find(@item.user_id).last_name %></dd>
  </dl>
  
  <dl>
    <dt><strong>Created:</strong>:</dt>
    <dd><%= @item.created_at %></dd>
  </dl>
  
  <dl>
    <dt><strong>Hits:</strong>:</dt>
    <dd><%= @item.hits %></dd>
  </dl>
  
  <dl>			
    <dt>Published:</dt>
    <dd>
      <% if @item.published
        %>
          <img src="/assets/tick_green_icon.png" alt="" />
        <%
        else
        %>
          <img src="/assets/unpublish_icon.png" alt="" />
        <%
        end
      %>
    </dd>
  </dl>
  
  <dl>			
    <dt>Description:</dt>
    <dd><%= @item.desc %></dd>
  </dl>
  
  <dl>
    <dt></dt>
    <dd><%=get_mediaelement_audio_player(@item.path.to_s).html_safe%></dd>
  </dl>
  
  <dl>			
    <dt></dt>
    <dd><%= link_to 'Back', admin_music_path %></dd>
  </dl>

</div>

app/views/admin/slides.html.erb
<% content_for :page_title do %>
  <title>ArtistNXT | Slides Manager</title>
<% end %>

<div class="profiletitle">Slides Manager</div>
<div class="clr">&nbsp;</div>

<div class="searchWrap">
	<div class="searchbox">
                <form id="searchForm" name="searchForm" action="" method="get">
                  <div class="searchboxinner">
                    <input type="text" name="search" class="textbox1" value="<%=h(@search)%>"/>
                    <input type="submit" value="Search" class="btn"/>
                    <input style="margin-left:4px;" type="button" class="btn" value="Reset" onclick="document.searchForm.search.value='';document.searchForm.submit();">
                  </div>
                </form>		
	</div>
	<div class="add-new"><%= link_to 'Add New', new_slide_path %></div>
	<div class="clr">&nbsp;</div>
</div>
<div class="tableWrap">
  <form id="dataFormSlide" name="dataFormSlide" action="" method="post">
  <div class="table-responsive">
    <table class="table">
           <thead>
                  <tr>
                    <th style="width: 50px;">#</th>
                    <th>Slide</th>
                    <th>Title</th>
                    <th style="width: 125px;">Published</th>
                    <th style="width: 125px;">Ordering<a href="javascript:void(0);" onclick="saveOrdering();"><%= image_tag("/assets/filesave_icon.png") %></a></th>
                    <th style="width: 150px;">Action</th>
                  </tr>
           </thead>
           <tbody>
                  <%                    
                    slideNo = 0
                    if params[:page].to_i > 1
		      slideNo = (params[:page].to_i - 1)*10
                    end
                    @slides.each do |slide|
                    slideNo = slideNo + 1
                  %>
                    <tr>
                      <td><%=slideNo%></td>
                      <td>
                        <%if slide.slide_image.to_s!=""
                        %>
                          <%= image_tag(slide.slide_image, :width=>125) %>
                        <%
                        else
                        %>
                          <%= image_tag("/assets/no_slider_image.png") %>
                        <%
                          end
                        %>
                      </td>
                      <td><%= link_to slide.title.html_safe, slide_path(slide) %></td>
                      <td>
                        <%if slide.published
                        %>
                          <img src="/assets/tick_green_icon.png" alt="" />
                        <%
                          else
                        %>
                          <img src="/assets/unpublish_icon.png" alt="" />
                        <%
                          end
                        %>
                        
                      </td>
                      <td><input type="text" name="ordering[<%=slide.id%>]" class="order_input" value="<%= slide.ordering.to_i %>"/></td>
                      <td>
                          <%= link_to image_tag("/assets/edit_icon.png"), edit_slide_path(slide) %>                          
                          &nbsp;&nbsp;&nbsp;
                          <%= link_to image_tag("/assets/delete_icon.png"), slide_path(slide),method: :delete, data: { confirm: 'Are you sure?' } %>
                      </td>
                    </tr>
                  <% end %>                  
           </tbody>
    </table>
    </div>
    <%= will_paginate @slides, :params=>{:search=>h(@search)} %>
  </form>
</div>
<script type="text/javascript">
function saveOrdering()
{
  if(jQuery('.order_input').length > 0)
  {    
    jQuery('#dataFormSlide').attr('action','<%=slides_save_ordering_path%>').submit();
  }
}
</script>