config/routes.rb
Artistnxt::Application.routes.draw do
  
  get "fanregister" => 'pages#fanregister', as: :fanregister
  get "admin/videos"
  get "/admin/video_details/:cid/" => 'admin#video_details', as: :admin_video_details
  match "/admin/save_video" => 'admin#save_video', via: [:post], as: :admin_save_video
  match "/admin/removevideo/:cid/" => "admin#removevideo", as: :removevideo, via: [:delete]
  get "admin/music"
  get "/admin/music_details/:cid/" => 'admin#music_details', as: :admin_music_details
  match "/admin/removemusic/:cid/" => "admin#removemusic", as: :removemusic, via: [:delete]
  
  get '/news/:id' => 'pages#readnews', as: :read_admin_news
  match '/news/save_ordering' => 'admin_news#save_ordering', via: [:post]
  resources :admin_news

  match '/cart/confirm' => 'carts#confirm', via: [:post]
  match '/confirm_music_purchase' => 'payment_notifications#confirm_music_purchase', via: [:post]
  get '/cart/checkout' => 'carts#checkout'
  match '/cart/remove_item' => 'carts#remove_item', via: [:delete]
  
  resources :order_items

  resources :orders

  resources :cart_items

  resources :carts

  get '/page/:alias' => 'pages#content_page', as: :content_page
  
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  
  match "payment/notifications" => 'payment_notifications#create', via: [:post]
  get "admin/settings"
  match "admin/save_settings" => 'admin#save_settings', via: [:post]  
  match "/admin/save_user" => 'admin#save_user', via: [:post], as: :admin_save_user
  match "/admin/save_new_user" => 'admin#save_new_user', via: [:post], as: :admin_save_new_user
  get "admin/dashboard"
  get "admin/users"
  get "admin/artists"
  get "admin/artist"
  get "admin/new_user"
  get "admin/edit_user"
  get "admin/fan"
  get "admin/fans"
  get "admin/users_json"
  get "admin/slides"
  get "profile/index"
  get "profile/follower_fans"
  get "profile/artist_following"
  
  match '/slides/save_ordering' => 'slides#save_ordering', via: [:post]
  match '/music_categories/save_ordering' => 'music_categories#save_ordering', via: [:post]
  match '/plans/save_ordering' => 'plans#save_ordering', via: [:post]
  match '/subscriptions/clear_invoice' => 'subscriptions#clear_invoice',via: [:get],  as: :clear_invoice
  match '/subscriptions/update' => 'subscriptions#update',via: [:post]
  match '/music_purchases/complete_order/:id' => 'music_purchases#complete_order',via: [:get], as: :admin_music_purchase_complete
  
  match '/application/upload_photo' => 'application#upload_photo', via: [:post]
  match '/application/check_email' => 'application#check_email', via: [:get]
  
  get '/artist/:id' => 'pages#dashboard', as: :artist_dashboard
  get '/fan/:id' => 'pages#dashboard', as: :fan_dashboard
  get '/dashboard/:id' => 'pages#dashboard', as: :user_dashboard
  get '/become_fan/:artistid/:fanid' => 'pages#become_fan', as: :become_fan
  get '/add_friend/:sender_id/:receiver_id' => 'profile#add_friend', as: :add_friend
  get '/remove_friend/:sender_id/:receiver_id' => 'profile#remove_friend', as: :remove_friend
  get '/accept_friend_request/:sender_id/:receiver_id' => 'profile#accept_friend_request', as: :accept_friend_request
  get '/my_friends' => 'profile#my_friends', as: :my_friends
  get '/peding_friend_requests' => 'profile#peding_friend_requests', as: :peding_friend_requests
  get '/awaiting_friend_requests' => 'profile#awaiting_friend_requests', as: :awaiting_friend_requests
  get '/artist_fantistics/:artist_id' => 'pages#artist_fantistics', as: :artist_fantistics
  
  get '/countries/get_states' => 'countries#get_country_states'
  
  get '/video/watch/:id' => 'videos#watch', as: :watch_video
  get '/video/remove_watch/:user_id/:id' => 'videos#remove_watch', as: :remove_video_watch
  get '/video/clear_watch_list' => 'videos#clear_watch_list', as: :clear_watch_list
  get '/video/make_favorite/:user_id/:id' => 'videos#make_favorite', as: :make_video_favorite
  get '/video/remove_favorite/:user_id/:id' => 'videos#remove_favorite', as: :remove_video_favorite
  get '/news/read/:id' => 'news#read', as: :read_news
  get '/event/details/:id' => 'events#details', as: :event_details
  
  get '/admin/make_featured_artist/:artist_id/:value' => 'admin#make_featured_artist', as: :make_featured_artist
  get '/admin/removeuser/:user_id/' => 'admin#removeuser', as: :removeuser
  
  get '/renew_subscription/:subscription_id' => 'pages#renew_subscription', as: :renew_subscription
  get '/confirmation_subscription/:subscription_id/:plan_id' => 'pages#confirmation_subscription', as: :confirmation_subscription
  get '/subscription_confirmed/:subscription_id/:plan_id' => 'pages#subscription_confirmed', as: :subscription_confirmed
  get '/pending_invoice/:subscription_id' => 'pages#pending_invoice', as: :pending_invoice
  get '/confirm_pending_invoice/:subscription_id' => 'pages#confirm_pending_invoice', as: :confirm_pending_invoice
  get '/download_music/:unqiue_key' => 'pages#download_music', as: :download_music
  get '/download_free_music/:id' => 'pages#download_free_music', as: :download_free_music
  get '/my_musics' => 'profile#my_musics', as: :my_musics
  get '/my_purchases' => 'profile#my_purchases', as: :my_purchases
  get '/my_music_sales' => 'profile#my_music_sales', as: :my_music_sales
  get '/favorite_videos' => 'profile#favorite_videos', as: :favorite_videos
  get '/watch_history' => 'profile#watch_history', as: :watch_history
  
  get '/my_order_details/:id' => 'profile#my_order_details',via: [:get], as: :my_order_details
  get '/pay_my_order/:id' => 'profile#pay_my_order',via: [:get], as: :pay_my_order
  
  match '/make_comment' => 'comments#create', via: [:post]
  
  resources :states

  resources :countries

  scope "/admin" do
    resources :contents
    resources :music_categories
    resources :music_purchases
    resources :plans
    resources :slides
    resources :subscriptions
  end

  devise_for :users, :controllers => { :registrations  => "users/registrations", :sessions => "users/sessions", :omniauth_callbacks => "users/omniauth_callbacks", :confirmations  => "users/confirmations" }
  
  devise_scope :user do
    get 'users' => 'devise/sessions#new'
    get 'signup/artist' => 'users/registrations#new', :user => { :user_type => 'artist' }
    get 'signup/fan' => 'users/registrations#new', :user => { :user_type => 'fan' }
    
    match 'users/omniauth_callbacks_confirm' => 'users/omniauth_callbacks#confirm_user_provider_signup', via: [:post]
  end
  
  resources :users do
    resources :videos, :audios, :news, :events
  end
  
  get "genres" => 'pages#genres'
  get "signup" => 'pages#signup'
  
  root 'pages#home'
  

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :cart_items, dependent: :destroy
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :cart_number %><br>
    <%= f.text_field :cart_number %>
  </div>
  <div class="field">
    <%= f.label :cart_total %><br>
    <%= f.text_field :cart_total %>
  </div>
  <div class="field">
    <%= f.label :ip_address %><br>
    <%= f.text_field :ip_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/checkout.html.erb
<% content_for :page_title do %>
  <title>ArtistNXT | Music Cart Checkout</title>
<% end %>
<div class="contentCol">
    <div class="content">
        <h2 class="logintitle2">Cart Checkout</h2>
        <div class="music_cart_wrap">
        <div class="table-responsive"> 
        <table cellpadding="0" cellspacing="0" border="0" class="table cart-table">
            <thead>
              <tr>          
                <th>Product Name</th>
                <th width="15%">Artist</th>
                <th>SubTotal</th>
                <th></th>
              </tr>
            </thead>
          
            <tbody>
              <% totalPrice = 0.00;
                @cart.cart_items.each do |item|
                totalPrice = (totalPrice + item.product_final_price)
              %>
                <tr>            
                  <td><%= item.product_name %></td>
                  <td width="15%">
                      <%=getMusicsArtistName(item.product_id,true)%>
                  </td>
                  <td>$<%= number_with_precision(item.product_final_price, precision: 2) %></td>
                  <td><%= link_to  image_tag("/assets/del.png") , item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
                <tr class="price-row">
                  <td width="15%">&nbsp;</td>
                  <td>&nbsp;</td>
                  <td class="pricelabel" align="right">Product price result:</td>
                  <td class="price">$<%=number_with_precision(totalPrice, precision: 2)%></td>          
                </tr>        
            </tbody>
          </table>
          </div>
          
          <form name="checkoutConfirm" id="checkoutConfirm" action="<%=cart_confirm_path%>" method="post">
              <div class="cart-comment">
                  <textarea name="customer_note" id="customer_note" placeholder="Your note" class="form-control"></textarea>
              </div>
              
              <div class="checkoutbutton">                  
                  <input type="submit" value="Confirm" class="checkoutbuttonwrap submit btn">  
              </div>
          </form>
        
        </div>
    </div>	
</div>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Cart number</th>
      <th>Cart total</th>
      <th>Ip address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.user_id %></td>
        <td><%= cart.cart_number %></td>
        <td><%= cart.cart_total %></td>
        <td><%= cart.ip_address %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @cart.user_id %>
</p>

<p>
  <strong>Cart number:</strong>
  <%= @cart.cart_number %>
</p>

<p>
  <strong>Cart total:</strong>
  <%= @cart.cart_total %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @cart.ip_address %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>